<a href="http://cocl.us/pytorch_link_top">
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/Pytochtop.png" width="750" alt="IBM Product " />
</a> 

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/cc-logo-square.png" width="200" alt="cognitiveclass.ai logo" />

<h1>Simple Dataset</h1> 

<h2>Table of Contents</h2>

<p>In this lab, you will construct a basic dataset by using PyTorch and learn how to apply basic transformations to it.</p> 
<ul>
    <li><a href="#Simple_Dataset">Simple dataset</a></li>
    <li><a href="#Transforms">Transforms</a></li>
    <li><a href="#Compose">Compose</a></li>
</ul>
<p>Estimated Time Needed: <strong>30 min</strong></p>
<hr>

<h2>Preparation</h2>

The following are the libraries we are going to use for this lab. The <code>torch.manual_seed()</code> is for forcing the random function to give the same number every time we try to recompile it.

In [1]:
# These are the libraries will be used for this lab.

import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

<!--Empty Space for separating topics-->

<h2 id="Simple_Dataset">Simple dataset</h2>

Let us try to create our own dataset class.

In [2]:
class toy_set(Dataset):
    
    def __init__(self, length=100, transform=None):
        self.len = length
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length)
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

Now, let us create our <code>toy_set</code> object, and find out the value on index 1 and the length of the inital dataset

In [3]:
# Create Dataset Object. Find out the value on index 1. Find out the length of Dataset Object.

our_dataset = toy_set()
print("Our toy_set object: ", our_dataset)
print("Value on index 0 of our toy_set object: ", our_dataset[0])
print("Our toy_set length: ", len(our_dataset))

Our toy_set object:  <__main__.toy_set object at 0x7f1376018c50>
Value on index 0 of our toy_set object:  (tensor([2., 2.]), tensor(1.))
Our toy_set length:  100


As a result, we can apply the same indexing convention as a <code>list</code>,
and apply the fuction <code>len</code> on the <code>toy_set</code> object. We are able to customize the indexing and length method by <code>def &#95;&#95;getitem&#95;&#95;(self, index)</code> and <code>def &#95;&#95;len&#95;&#95;(self)</code>.

Now, let us print out the first 3 elements and assign them to x and y:

In [4]:
# Use loop to print out first 3 elements in dataset

for i in range(3):
    x, y=our_dataset[i]
    print("index: ", i, '; x:', x, '; y:', y)

index:  0 ; x: tensor([2., 2.]) ; y: tensor(1.)
index:  1 ; x: tensor([2., 2.]) ; y: tensor(1.)
index:  2 ; x: tensor([2., 2.]) ; y: tensor(1.)


The dataset object is an Iterable; as a result, we  apply the loop directly on the dataset object 

In [5]:
for x,y in our_dataset:
    print(' x:', x, 'y:', y)

 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.]) y: tensor(1.)
 x: tensor([2., 2.])

<!--Empty Space for separating topics-->

<h3>Practice</h3>

Try to create an <code>toy_set</code> object with length <b>50</b>. Print out the length of your object.

In [6]:
# Practice: Create a new object with length 50, and print the length of object out.

# Type your code here
from numpy.random import randn

class toy_set(Dataset):
    
    def __init__(self, length, transform=None):
        self.len = length
        self.x = torch.from_numpy(randn(length, 3))
        self.y = torch.ones(length)
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len
    
new_data = toy_set(length=50)
for x, y in new_data:
    print((x, y))

(tensor([0.5330, 0.0512, 0.0910], dtype=torch.float64), tensor(1.))
(tensor([-0.7819,  1.7683, -0.5925], dtype=torch.float64), tensor(1.))
(tensor([-0.5654, -1.2602,  2.2674], dtype=torch.float64), tensor(1.))
(tensor([-3.2757,  0.6825, -0.1373], dtype=torch.float64), tensor(1.))
(tensor([-0.0192, -1.0548,  1.0375], dtype=torch.float64), tensor(1.))
(tensor([1.4275, 0.6658, 1.3370], dtype=torch.float64), tensor(1.))
(tensor([ 0.4302, -1.2164,  0.3377], dtype=torch.float64), tensor(1.))
(tensor([0.3932, 0.5788, 1.8006], dtype=torch.float64), tensor(1.))
(tensor([ 0.1507,  0.2461, -0.1819], dtype=torch.float64), tensor(1.))
(tensor([ 0.2164,  0.2298, -0.6445], dtype=torch.float64), tensor(1.))
(tensor([0.7411, 0.3782, 0.1760], dtype=torch.float64), tensor(1.))
(tensor([ 0.2896, -0.1323, -0.2513], dtype=torch.float64), tensor(1.))
(tensor([ 0.6379, -1.7868, -0.8313], dtype=torch.float64), tensor(1.))
(tensor([-0.0394,  1.0348,  1.8472], dtype=torch.float64), tensor(1.))
(tensor([ 0.9431, 

Double-click <b>here</b> for the solution.
<!-- 
my_dataset = toy_set(length = 50)
print("My toy_set length: ", len(my_dataset))
-->

<!--Empty Space for separating topics-->

<h2 id="Transforms">Transforms</h2>

You can also create a class for transforming the data. In this case, we will try to add 1 to x and multiply y by 2:

In [7]:
class add_mul(object):
    
    def __init__(self, add_x, mul_y):
        self.add_x = add_x
        self.mul_y = mul_y
        
    def __call__(self, sample):
        return sample[0] + self.add_x, sample[1] * self.mul_y

<!--Empty Space for separating topics-->

Now, create a transform object:.

In [9]:
# Create an add_mult transform object, and an toy_set object

a_m = add_mul(add_x=2, mul_y=3)
data_set = toy_set(length=20)

Assign the outputs of the original dataset to <code>x</code> and <code>y</code>. Then, apply the transform <code>add_mult</code> to the dataset and output the values as <code>x_</code> and <code>y_</code>, respectively: 

In [10]:
# Use loop to print out first 10 elements in dataset

for i in range(10):
    x, y = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_, y_ = a_m(data_set[i])
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)

Index:  0 Original x:  tensor([-0.4663,  1.1305,  0.1548], dtype=torch.float64) Original y:  tensor(1.)
Index:  0 Transformed x_: tensor([1.5337, 3.1305, 2.1548], dtype=torch.float64) Transformed y_: tensor(3.)
Index:  1 Original x:  tensor([-0.7209,  0.4311,  0.6368], dtype=torch.float64) Original y:  tensor(1.)
Index:  1 Transformed x_: tensor([1.2791, 2.4311, 2.6368], dtype=torch.float64) Transformed y_: tensor(3.)
Index:  2 Original x:  tensor([-0.5333, -0.5936,  1.2296], dtype=torch.float64) Original y:  tensor(1.)
Index:  2 Transformed x_: tensor([1.4667, 1.4064, 3.2296], dtype=torch.float64) Transformed y_: tensor(3.)
Index:  3 Original x:  tensor([-1.4864,  1.8422,  1.9957], dtype=torch.float64) Original y:  tensor(1.)
Index:  3 Transformed x_: tensor([0.5136, 3.8422, 3.9957], dtype=torch.float64) Transformed y_: tensor(3.)
Index:  4 Original x:  tensor([ 0.9255, -1.9691, -2.1971], dtype=torch.float64) Original y:  tensor(1.)
Index:  4 Transformed x_: tensor([ 2.9255,  0.0309, 

As the result, <code>x</code> has been added by 1 and y has been multiplied by 2, as <i>[2, 2] + 1 = [3, 3]</i> and <i>[1] x 2 = [2]</i>

<!--Empty Space for separating topics-->

We can apply the transform object every time we create a new <code>toy_set object</code>? Remember, we have the constructor in toy_set class with the parameter <code>transform = None</code>.
When we create a new object using the constructor, we can assign the transform object to the parameter transform, as the following code demonstrates.

In [11]:
# Create a new data_set object with add_mult object as transform

cust_data_set = toy_set(length=20, transform = a_m)

This applied <code>a_m</code> object (a transform method) to every element in <code>cust_data_set</code> as initialized. Let us print out the first 10 elements in <code>cust_data_set</code> in order to see whether the <code>a_m</code> applied on <code>cust_data_set</code>

In [12]:
# Use loop to print out first 10 elements in dataset

for i in range(10):
    x, y = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_, y_ = cust_data_set[i]
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)

Index:  0 Original x:  tensor([-0.4663,  1.1305,  0.1548], dtype=torch.float64) Original y:  tensor(1.)
Index:  0 Transformed x_: tensor([0.3462, 0.5173, 1.2921], dtype=torch.float64) Transformed y_: tensor(1.)
Index:  1 Original x:  tensor([-0.7209,  0.4311,  0.6368], dtype=torch.float64) Original y:  tensor(1.)
Index:  1 Transformed x_: tensor([0.6977, 0.0045, 0.0832], dtype=torch.float64) Transformed y_: tensor(1.)
Index:  2 Original x:  tensor([-0.5333, -0.5936,  1.2296], dtype=torch.float64) Original y:  tensor(1.)
Index:  2 Transformed x_: tensor([-0.8482, -1.0351,  0.2825], dtype=torch.float64) Transformed y_: tensor(1.)
Index:  3 Original x:  tensor([-1.4864,  1.8422,  1.9957], dtype=torch.float64) Original y:  tensor(1.)
Index:  3 Transformed x_: tensor([0.5943, 1.3780, 0.2331], dtype=torch.float64) Transformed y_: tensor(1.)
Index:  4 Original x:  tensor([ 0.9255, -1.9691, -2.1971], dtype=torch.float64) Original y:  tensor(1.)
Index:  4 Transformed x_: tensor([-0.5493, -1.860

The result is the same as the previous method.

<!--Empty Space for separating topics-->

In [ ]:
# Practice: Construct your own my_add_mult transform. Apply my_add_mult on a new toy_set object. Print out the first three elements from the transformed dataset.

# Type your code here.

Double-click <b>here</b> for the solution.
<!-- 
class my_add_mult(object):   
    def __init__(self, add = 2, mul = 10):
        self.add=add
        self.mul=mul
        
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.add
        y = y + self.add
        x = x * self.mul
        y = y * self.mul
        sample = x, y
        return sample
        
       
my_dataset = toy_set(transform = my_add_mult())
for i in range(3):
    x_, y_ = my_dataset[i]
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)
    
 -->

<!--Empty Space for separating topics-->

<h2 id="Compose">Compose</h2>

You can compose multiple transforms on the dataset object. First, import <code>transforms</code> from <code>torchvision</code>:

In [13]:
# Run the command below when you do not have torchvision installed
# !conda install -y torchvision

from torchvision import transforms

Then, create a new transform class that multiplies each of the elements by 100: 

In [14]:
# Create tranform class mult

class mult(object):
    
    # Constructor
    def __init__(self, mult = 100):
        self.mult = mult
        
    # Executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mult
        y = y * self.mult
        sample = x, y
        return sample

Now let us try to combine the transforms <code>add_mult</code> and <code>mult</code>

In [16]:
# Combine the add_mult() and mult()

data_transform = transforms.Compose([add_mul(add_x=3, mul_y=4), mult()])
print("The combination of transforms (Compose): ", data_transform)


The combination of transforms (Compose):  Compose(
)


The new <code>Compose</code> object will perform each transform concurrently as shown in this figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.3.1_trasform.png" width="500" alt="Compose PyTorch">

In [17]:
data_transform(data_set[0])

(tensor([253.3713, 413.0548, 315.4776], dtype=torch.float64), tensor(400.))

In [19]:
x,y=data_set[0]
x_,y_=data_transform(data_set[0])
print( 'Original x: ', x, 'Original y: ', y)

print( 'Transformed x_:', x_, 'Transformed y_:', y_)

Original x:  tensor([-0.4663,  1.1305,  0.1548], dtype=torch.float64) Original y:  tensor(1.)
Transformed x_: tensor([253.3713, 413.0548, 315.4776], dtype=torch.float64) Transformed y_: tensor(400.)


Now we can pass the new <code>Compose</code> object (The combination of methods <code>add_mult()</code> and <code>mult</code>) to the constructor for creating <code>toy_set</code> object.

In [21]:
# Create a new toy_set object with compose object as transform

compose_data_set = toy_set(length=20,transform = data_transform)

Let us print out the first 3 elements in different <code>toy_set</code> datasets in order to compare the output after different transforms have been applied: 

In [22]:
# Use loop to print out first 3 elements in dataset

for i in range(3):
    x, y = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_, y_ = cust_data_set[i]
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)
    x_co, y_co = compose_data_set[i]
    print('Index: ', i, 'Compose Transformed x_co: ', x_co ,'Compose Transformed y_co: ',y_co)

Index:  0 Original x:  tensor([-0.4663,  1.1305,  0.1548], dtype=torch.float64) Original y:  tensor(1.)
Index:  0 Transformed x_: tensor([0.3462, 0.5173, 1.2921], dtype=torch.float64) Transformed y_: tensor(1.)
Index:  0 Compose Transformed x_co:  tensor([ 0.9376,  0.3512, -0.3920], dtype=torch.float64) Compose Transformed y_co:  tensor(1.)
Index:  1 Original x:  tensor([-0.7209,  0.4311,  0.6368], dtype=torch.float64) Original y:  tensor(1.)
Index:  1 Transformed x_: tensor([0.6977, 0.0045, 0.0832], dtype=torch.float64) Transformed y_: tensor(1.)
Index:  1 Compose Transformed x_co:  tensor([-0.7086,  0.0253, -1.4833], dtype=torch.float64) Compose Transformed y_co:  tensor(1.)
Index:  2 Original x:  tensor([-0.5333, -0.5936,  1.2296], dtype=torch.float64) Original y:  tensor(1.)
Index:  2 Transformed x_: tensor([-0.8482, -1.0351,  0.2825], dtype=torch.float64) Transformed y_: tensor(1.)
Index:  2 Compose Transformed x_co:  tensor([ 2.0352,  1.1366, -1.7693], dtype=torch.float64) Compos

Let us see what happened on index 0. The original value of <code>x</code> is <i>[2, 2]</i>, and the original value of <code>y</code> is [1]. If we only applied <code>add_mult()</code> on the original dataset, then the <code>x</code> became <i>[3, 3]</i> and y became <i>[2]</i>. Now let us see what is the value after applied both <code>add_mult()</code> and <code>mult()</code>. The result of x is <i>[300, 300]</i> and y is <i>[200]</i>. The calculation which is equavalent to the compose is <i> x = ([2, 2] + 1) x 100 = [300, 300], y = ([1] x 2) x 100 = 200</i>

<h3>Practice</h3>

Try to combine the <code>mult()</code> and <code>add_mult()</code> as <code>mult()</code> to be executed first. And apply this on a new <code>toy_set</code> dataset. Print out the first 3 elements in the transformed dataset.

In [36]:
# Practice: Make a compose as mult() execute first and then add_mult(). Apply the compose on toy_set dataset. Print out the first 3 elements in the transformed dataset.

# Type your code here.

from torchvision import transforms

class mult(object):
    
    def __init__(self, y_mul=2):
        self.y_mul = y_mul
        
    def __call__(self, dt):
        return dt[0], dt[1] * self.y_mul
    
    
class add_mul(object):
    
    def __init__(self, x_add=3, y_mul=10):
        self.x_add = x_add
        self.y_mul = y_mul
        
    def __call__(self, dt):
        return dt[0]+self.x_add, dt[1]*self.y_mul
    
    
dt_transform = transforms.Compose([mult(), add_mul()])
dt = toy_set(length=10, transform=dt_transform)
for i in range(3):
    print(dt[i])
    
    
dt[:3]

(tensor([ 0.9254, -0.0984, -1.1893], dtype=torch.float64), tensor(1.))
(tensor([-1.4233, -1.6722,  0.5870], dtype=torch.float64), tensor(1.))
(tensor([1.3945, 1.1741, 0.9525], dtype=torch.float64), tensor(1.))


(tensor([[ 0.9254, -0.0984, -1.1893],
         [-1.4233, -1.6722,  0.5870],
         [ 1.3945,  1.1741,  0.9525]], dtype=torch.float64),
 tensor([1., 1., 1.]))

Double-click <b>here</b> for the solution.
<!--
my_compose = transforms.Compose([mult(), add_mult()])
my_transformed_dataset = toy_set(transform = my_compose)
for i in range(3):
    x_, y_ = my_transformed_dataset[i]
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)
-->

<!--Empty Space for separating topics-->

<a href="http://cocl.us/pytorch_link_bottom">
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/notebook_bottom%20.png" width="750" alt="PyTorch Bottom" />
</a>

<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Other contributors: <a href="https://www.linkedin.com/in/michelleccarey/">Michelle Carey</a>, <a href="www.linkedin.com/in/jiahui-mavis-zhou-a4537814a">Mavis Zhou</a> 

<hr>

Copyright &copy; 2018 <a href="cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu">cognitiveclass.ai</a>. This notebook and its source code are released under the terms of the <a href="https://bigdatauniversity.com/mit-license/">MIT License</a>.